### PR TITLE
First attempt at disentangling Event from Effect

### PR DESCRIPTION
**Pull request by mikesol**
There's one issue with this that it rewrites the definition of `fix` pretty significantly. I'm not sure if this introduces breaking changes: we'd need to add tests for `fix` to determine if that's the case.

### CODE REVIEW

**Comment by MonoidMusician** [comment]
Looks pretty good. Why are you using `MonadST` over `MonadEffect`? Other than to break the compiler ;)

I think `fix` has the same issue with subscriptions that we have been talking about with memoization. If you have a fixpoint effect based on a setTimeout loop, it might have different behavior for different subscribers. I don't know what the correct behavior is.

Also are you sure that `memoize` actually memoizes? It looks like it creates a new event for each subscriber … maybe it is the one that needs `unsafePerformEffect create`. Which I think is fine – I think you can give it this type signature instead:
```create
  :: forall m1 m2 s a
   . MonadST s m1
  => MonadST s m2
  => m1 (AnEventIO m2 a)
```

**Comment by mikesol** [comment]
> Looks pretty good. Why are you using `MonadST` over `MonadEffect`? Other than to break the compiler ;)

As if breaking the compiler isn't reason enough! :-P
I'm experimenting with SSR in Deku. MonadST allows you to have "pure" events, which can be used to render HTML on a first pass.

Re memoization, it could be that I've broken it, although so far my examples that use it in wags and Deku work and I think it passes the test as well. Could you try to write a test that breaks it?

Re fix, yes you're right it's no longer memoized by default, but maybe that's ok?

**Comment by MonoidMusician** [comment]
Oh I see you changed the memoized a lot, it doesn't work how I expected. I guess it still kind of memoizes, just not at the level I expected since duplicate subscriptions from _outside_ are not memoized. How do you actually use it? Like, why would you expect the `Event a -> r` continuation to subscribe multiple times, and not the resulting `Event r` to receive multiple subscriptions?

**Comment by mikesol** [comment]
> Oh I see you changed the memoized a lot, it doesn't work how I expected. I guess it still kind of memoizes, just not at the level I expected since duplicate subscriptions from _outside_ are not memoized. How do you actually use it? Like, why would you expect the `Event a -> r` continuation to subscribe multiple times, and not the resulting `Event r` to receive multiple subscriptions?

Yeah apologies for the change, I should have given you the heads up. The new implementation has similar mechanics to the previous one (mutualizes a single emitter over several subscribers) but it is in PS & not JS.

I use it similarly to how the previous one was used, ie https://github.com/mikesol/purescript-wags/blob/e646eabf7b39661362e5a9067fc0ab6ca6f332ed/examples/atari-speaks/AtariSpeaks.purs#L101. It can now be nestled in arbitrary event chains without needing to be passed down from `Effect`. The pattern, then, is to treat memoize as a closure where everything that depends upon it is inside the closure. That's less flexible than working with something created in `Effect` but in general it's felt more ergonomic when you're in event-land.

**Comment by MonoidMusician** [comment]
Hm that's really interesting. It does seem to fit well into the framework, and requires no unsafe effects either! So yeah, if it works go for it, I have no other feedback.

**Comment by mikesol** [comment]
I've tested this with the fixed point combinator in `wags` (which is pretty gnarly) and it works, so I'm going to merge and release! There could be some optimizations to do, but in general I think it's fit to fly. The next step after updating Behaviors is taking Deku and Wags out of their monomorphic `Event` definitions and using `AnEvent m`. This'll be a bit clunky as both frameworks use `AVar` in certain places, but all of the `AVar` logic can be replaced with `Ref`.

**Pull request merged**
