### PR TITLE
Adds different flavors of event

### PR DESCRIPTION
**Pull request by mikesol**
Sketch for the eventual `v1.5.0` branch.

### CODE REVIEW

**Comment by MonoidMusician** [comment]
Looks good!

I think `bang` and `empty` can use a new function `unsafeMarkMemoized :: Event a -> Event a` that just sets the flag on the event and returns it. That is, we don't actually need the memoization machinery (keeping track of subscriptions …) for them since they are so trivial. Other combinators like filtering probably also don't need the memoization – but we need to indicate they still preserve memoizability. The real cases where we do want the memoization is mostly just combinators that map a function over the event, from what I understand!

And then the other goal is seeing if we can interleave pure and impure events by wrapping them in a combined datatype.

I'll think about `apply` a bit more. One ameliorating effect is that the order of subscribers should be deterministic. Maybe that should be added to the contract somewhere that subscribers are notified in the order they subscribed. It probably isn't _so_ bad to have duplicate events in some cases if they happen so close – although for events that accumulate it will certainly throw it off, so that makes for buggy code! Almost need to separate scheduling from data flow …

**Comment by MonoidMusician** [comment]
Along the lines of separating scheduling from dataflow, we could keep track of the leaf events that control the timing of each event, and then we could re-subscribe to them directly to avoid the issues with concurrent events in `apply`.

Something like `apply f a = sampleOn_ (naiveApply f a) (sources f <> sources a)`.
This could be optimized by some special cases: if `sources f` is a subset of `sources a`, then it can just be `apply f a = sampleOn f a`, and vice-versa, and when they're disjoint then it's just `naiveApply`, etc.

Without the optimizations, we would probably end up with a _lot_ of transitive subscriptions. But with the optimizations, the resubscription would only happen when the events depend on some but not all of the same subscriptions.

A way to avoid that would be to have events keep track of who is triggering them, thus dropping events from the first one to come in when we know the second will also be triggered – but I'm not sure if that's feasible.

It would be deeply magical in some sense, but I think it would also capture an intuition people have.

Oh I guess I have no idea how it would interact with filtering 😅 Hm

Maybe this is why they leave it to users to deal with the race conditions, it's just so hard to do it automatically.

**Comment by mikesol** [comment]
Thanks for this feedback! I love these ideas, totally nerd-sniped 😍
If you have the chance, could you run the tests and take a look at the performance benchmarks? I can't come up with a test case yet where memoization shows any appreciable gains, and before adding it, we should know a category where it moves the needle performance-wise. As I mentioned in https://github.com/mikesol/purescript-wags/issues/52#issuecomment-1094298811, the performance is still so far from its imperative counterpart that, in real-world cases, memoization doesn't yet create opportunities to lean into the event-based architecture more.

**Comment by mikesol** [comment]
As a motivating example that's sort of quixotic, imagine that I have:

```purescript
let a = pi * 4.0
let b = a * 440.0
let c = a * 880.0
let d = a * 1200.0
[a,b,c,d]
```

It would be amazing if:

```purescript
let pie = map (mul pi)(bang 4.0) in map (mul 440.0) pie <|> map (mul 880.0) pie <|> map (mul 1200.0) pie
```

had a competitive performance profile at scale.

**Pull request merged**
